### ISSUE TITLE
[Animals Need Water] Cannot enter on some buildings

### ISSUE THREAD

**Issue by faatihf** [gzhynko/stardew-mods#1]
I think I got a bug when try to access my slime hutch and shed. I use mods to change both appearance (and probably their tile sheet). I cannot enter because (i think) it says this mod change the farmer warp location or something. I attached the log.
https://smapi.io/log/9817fbca9acd43e1b275f34ab712fce7

Mods that have the prob :
https://www.nexusmods.com/stardewvalley/mods/2709
https://www.nexusmods.com/stardewvalley/mods/1993

**Comment by gzhynko** [comment]
Fixed in 694d83774bf17dab9f1fee21d4db7068efbc6b3c. Thanks!
