### ISSUE TITLE
Animal Need Water API:DoesAnimalHaveAccessToWater

### ISSUE THREAD

**Issue by Prism-99** [gzhynko/stardew-mods#10]
I was trying out your API and I was getting false result from Animals that I know had water.  I noticed you store the indoor name in lowercase, but in the API call DoesAnimalHaveAccessToWater the 2 nameofIndoors checks are not transformed tolower.  I did a local compile with the tolowers added and the false negatives went away.

Just found out about this mod, nice addition to the game play.

**Comment by gzhynko** [comment]
Didn't notice that, thanks!
