### ISSUE TITLE
[Dialogue Box Redesign] Make compatible with Stardew Valley 1.6 and SMAPI 4.0

### ISSUE THREAD

**Issue by DataGoblin** [gzhynko/stardew-mods#15]
![image](https://github.com/gzhynko/stardew-mods/assets/88795284/54654243-e3f8-4c61-a2a9-9e1940426efb)

With the recent update to Stardew and SMAPI. This mod is no longer functioning for new versions. 

Leaving this issue here for record. If anyone can help update this mod, thank you!

**Comment by gzhynko** [comment]
Hey, just pushed e510e8e with updates for sdv 1.6, should be up on Nexus soon once I get each mod ready for release.
